# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_status', models.BooleanField()),
                ('message_text', models.TextField()),
            ],
        ),
    ]
