# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_messagemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleModel',
        ),
    ]
